### ISSUE TITLE
Can this model be used for french data ?

### ISSUE THREAD

**Issue by keloemma** [crux82/ganbert#2]
I have small data in french, I need to classify in three different classes but  since the data (sentences) are really small, is using this type of system really helpful and If I used it , is it difficult to adapt it for french classification ?

**Comment by kamei86i** [comment]
Hi, we didn't specifically tried the model for languages other than English. However, I think that if you use the multilingual BERT model as starting point (https://github.com/google-research/bert/blob/master/multilingual.md) you should be able to have results very similar to what we measured for the English language. You should be able to use the multilingual BERT model without any code modification.
