### ISSUE TITLE
Code for tensorflow 2.*

### ISSUE THREAD

**Issue by Hayat2018** [crux82/ganbert#6]
Its a might job done, do appreciate all the efforts. However, i just want to know that if i want to run the code on googl colab and google colab supports tensorflow 2.* version only. All the code written for tensorflow 1.* some time have 'contrib' which cannot be converted automatically to tensorflow 2 So,.
What i want to say, is the GANBert code available for tensorflow 2.* version?
My apologies if i asked this at wrong place.

Kind Regards.

**Comment by crux82** [comment]
Unfortunately the code is not available for Tensorflow 2.* 
We are considering whether to convert it to Tensorflow 2.*  or Pytorch. 

Bests 

Danilo

**Comment by cuczy** [comment]
It's a great job ,hope you can convert it to Pytorch

Best
zy
