### ISSUE TITLE
About the [balance]

### ISSUE THREAD

**Issue by colourful-tree** [crux82/ganbert#7]
Hi, excellent work!

But, i am a little confused about the [balance], which is used for oversample instance？
And why we need oversample?
https://github.com/crux82/ganbert/blob/32e992281229ac6678350f338480cd29dacbf578/ganbert.py#L280

**Comment by crux82** [comment]
Hi 

As written in the paper, we replicated the labeled examples of a logarithmic factor. This guarantees the presence of some labeled instances in each batch to avoid divergences due to the unsupervised component of the adversarial training.

Hope it helps. 
Bests

Danilo
