### ISSUE TITLE
Question about sentence pair (MNLI) task?

### ISSUE THREAD

**Issue by sb1992** [crux82/ganbert#9]
What will be the format of the data to run the model for sentence pair task like MNLI mentioned in the paper? I would also like to try for other sentence pair tasks as well, so was curious how should i format both labelled and unlabelled data and if there would be any changes in the code?

**Comment by kamei86i** [comment]
Hi,

sorry for the late reply. You basically need to write your data processor that accepts as input a file in whatever format you'd like. The data processor is responsible for creating the example to be used with the GAN-BERT model. The example is an instance of the InputExample class.

In https://github.com/crux82/ganbert/blob/32e992281229ac6678350f338480cd29dacbf578/data_processors.py#L94 you can find an example of the data processor we wrote for the QcFine task, which is however a single sentence task. What you'll need to do is to parse your input file, and then create the right example, as in https://github.com/crux82/ganbert/blob/32e992281229ac6678350f338480cd29dacbf578/data_processors.py#L128. Notice that for sentence pairs you would need to pass also the 'text_b' argument to InputExample.
